name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn

      - name: Clean, build, format, lint, package, and test
        run: |
          yarn all

      - name: Check if packaged properly
        run: |
          # If there are any unstaged or untracked files in 'dist/', then the action wasn't packaged properly
          if git diff --name-only | grep '^dist/' || git ls-files --other --exclude-standard | grep '^dist/'; then
            echo "You didn't package the action properly before pushing to remote." \
            echo "Always run 'yarn all' before staging a commit."
            echo "Below are the modified files in 'dist/' after running 'yarn && rm -rf dist/ && yarn all':"
            git diff --name-only | grep '^dist/'
            git ls-files --other --exclude-standard | grep '^dist/'
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: files
        name: Run the action
        uses: jomendez/changed-files-action@1.0
