name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: files
        name: Run the action
        uses: jomendez/changed-files-action@1.0
